<a href="https://colab.research.google.com/github/KiranJoshi25/DataVizFall2020_Colab-/blob/master/Folium_States_question.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import pandas as pd

In [24]:
import folium

In [25]:

db = "https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv"
map_data = "https://raw.githubusercontent.com/KiranJoshi25/DataVizFall2020_Colab-/master/cb_2018_us_state_20m.json"
df = pd.read_csv(db)
df.head(5)

         date     county       state     fips  cases  deaths
0  2020-01-21  Snohomish  Washington  53061.0      1       0
1  2020-01-22  Snohomish  Washington  53061.0      1       0
2  2020-01-23  Snohomish  Washington  53061.0      1       0
3  2020-01-24       Cook    Illinois  17031.0      1       0
4  2020-01-24  Snohomish  Washington  53061.0      1       0

In [26]:
map_data = "https://raw.githubusercontent.com/KiranJoshi25/DataVizFall2020_Colab-/master/cb_2018_us_state_20m.json"
state = pd.read_json(map_data)
state['features'].iloc[0]

{'geometry': {'coordinates': [[[[-76.046213, 38.025532999999996],
     [-76.04652999999999, 37.953586],
     [-75.98464799999999, 37.938120999999995],
     [-75.98008899999999, 38.004891],
     [-76.00733699999999, 38.036705999999995],
     [-76.046213, 38.025532999999996]]],
   [[[-79.47666199999999, 39.721078],
     [-79.482366, 39.531689],
     [-79.484372, 39.344300000000004],
     [-79.486873, 39.205960999999995],
     [-79.424413, 39.228170999999996],
     [-79.35374999999999, 39.278039],
     [-79.283723, 39.30964],
     [-79.26239211717609, 39.3262438284674],
     [-79.16649699999999, 39.400887999999995],
     [-79.091329, 39.472407],
     [-79.0674474080724, 39.4728086991282],
     [-79.035623, 39.473344],
     [-78.956751, 39.440264],
     [-78.942618, 39.479614],
     [-78.851016, 39.554044],
     [-78.77114, 39.638387],
     [-78.73904999999999, 39.609697],
     [-78.707098, 39.555856999999996],
     [-78.6550361715467, 39.544382241083696],
     [-78.590654, 39.530192],
     [-78.4682695950029, 39.5262242704717],
     [-78.460951, 39.525987],
     [-78.43817899999999, 39.563524],
     [-78.382959, 39.622246],
     [-78.3327880214991, 39.6285275964988],
     [-78.31303299999999, 39.631001],
     [-78.22507499999999, 39.658878],
     [-78.08225999999999, 39.671166],
     [-78.02762910017319, 39.6206559623441],
     [-78.006734, 39.601337],
     [-77.92598799999999, 39.607642],
     [-77.829814, 39.587288],
     [-77.823762, 39.525907],
     [-77.81094389626219, 39.5007391665665],
     [-77.79820099999999, 39.475719],
     [-77.740012, 39.401694],
     [-77.74593, 39.353221],
     [-77.71951899999999, 39.321314],
     [-77.6776957620787, 39.317940817088],
     [-77.66613, 39.317008],
     [-77.588235, 39.301955],
     [-77.553114, 39.279267999999995],
     [-77.496606, 39.251045],
     [-77.4600656264978, 39.21884294385939],
     [-77.45988299999999, 39.218682],
     [-77.48597099999999, 39.185665],
     [-77.521222, 39.161057],
     [-77.51992899999999, 39.120925],
     [-77.481279, 39.105658],
     [-77.462617, 39.076248],
     [-77.359702, 39.062004],
     [-77.33003770595408, 39.055952113491],
     [-77.310705, 39.052008],
     [-77.248403, 39.026908999999996],
     [-77.2484037049754, 39.026888354292296],
     [-77.249803, 38.985909],
     [-77.202502, 38.967909999999996],
     [-77.14660099999999, 38.96421],
     [-77.1197891567342, 38.9343765552932],
     [-77.119759, 38.934343],
     [-77.041018, 38.995548],
     [-77.002546244247, 38.9655317004459],
     [-76.909393, 38.892852],
     [-76.979497, 38.837812],
     [-77.039006, 38.791644999999995],
     [-77.0392398850823, 38.785336325623604],
     [-77.0406725707781, 38.746691930482896],
     [-77.040998, 38.737913999999996],
     [-77.05319899999999, 38.709914999999995],
     [-77.079499, 38.709514999999996],
     [-77.08578476515639, 38.7052812818324],
     [-77.13250099999999, 38.673815999999995],
     [-77.1302, 38.635017],
     [-77.12908399999999, 38.614363999999995],
     [-77.183767, 38.600699],
     [-77.246584, 38.538340999999996],
     [-77.259962, 38.435821],
     [-77.21118799999999, 38.380662],
     [-77.123325, 38.410646],
     [-77.07548899999999, 38.42471],
     [-77.01637099999999, 38.445572],
     [-77.001638, 38.421952],
     [-76.975492, 38.347327],
     [-76.92217699999999, 38.311339],
     [-76.86429199999999, 38.268944999999995],
     [-76.8270361292819, 38.2583001006141],
     [-76.805949, 38.252275],
     [-76.740055, 38.235226999999995],
     [-76.673462, 38.234401],
     [-76.590637, 38.214211999999996],
     [-76.54038, 38.152991],
     [-76.481036, 38.115873],
     [-76.430425, 38.119383],
     [-76.37178999999999, 38.079564999999995],
     [-76.322093, 38.036502999999996],
     [-76.330794, 38.099331],
     [-76.32013599999999, 38.138338999999995],
     [-76.353516, 38.178135],
     [-76.392668, 38.239663],
     [-76.374481, 38.296347999999995],
     [-76.402894, 38.311402],
     [-76.400194624698, 38.3198719439614],
     [-76.387002, 38.361267],
     [-76.393378, 38.389477],
     [-76.450937, 38.442422],
     [-76.492699, 38.482849],
     [-76.517506, 38.539148999999995],
     [-76.51127799999999, 38.615745],
     [-76.52892299999999, 38.663889],
     [-76.52709254739419, 38.7127503012383],
     [-76.52665499999999, 38.72443],
     [-76.55874299999999, 38.756352],
     [-76.526979, 38.787016],
     [-76.48987799999999, 38.838715],
     [-76.516944, 38.851157],
     [-76.49068, 38.884814],
     [-76.4739761636555, 38.9026933786299],
     [-76.46938, 38.907613],
     [-76.45027999999999, 38.941113],
     [-76.47128099999999, 38.956512],
     [-76.448981, 38.982811],
     [-76.39408, 39.011311],
     [-76.420394, 39.042069999999995],
     [-76.42186, 39.081441999999996],
     [-76.428681, 39.131709],
     [-76.525785, 39.177907999999995],
     [-76.5040085909181, 39.199286249126004],
     [-76.498384, 39.204808],
     [-76.463483, 39.205908],
     [-76.425281, 39.205708],
     [-76.39550899999999, 39.231702],
     [-76.349994, 39.248822],
     [-76.3254183419569, 39.2729050860827],
     [-76.29660899999999, 39.301137],
     [-76.224161, 39.352779999999996],
     [-76.146373, 39.40531],
     [-76.060931, 39.452208],
     [-76.0376462883158, 39.4526423823093],
     [-76.012312, 39.453115],
     [-76.00688, 39.414527],
     [-76.040962, 39.394237],
     [-76.0614988219557, 39.3877481141151],
     [-76.11052699999999, 39.372257],
     [-76.159673, 39.335909],
     [-76.17770399999999, 39.298701],
     [-76.211253, 39.269812],
     [-76.243166, 39.213362],
     [-76.278527, 39.145764],
     [-76.246481, 39.119588],
     [-76.233457, 39.091384999999995],
     [-76.231765, 39.018518],
     [-76.2650366404087, 39.0285509553488],
     [-76.301847, 39.039651],
     [-76.322296, 39.006375],
     [-76.361727, 38.939175],
     [-76.37620199999999, 38.850460999999996],
     [-76.334019, 38.860237999999995],
     [-76.31794699999999, 38.911311999999995],
     [-76.250868, 38.92825],
     [-76.203638, 38.928382],
     [-76.205063, 38.892725999999996],
     [-76.196868759948, 38.8557419634207],
     [-76.19109, 38.82966],
     [-76.21932799999999, 38.812371],
     [-76.271575, 38.851771],
     [-76.310081, 38.796845999999995],
     [-76.379739, 38.788314],
     [-76.39035, 38.757003999999995],
     [-76.340543, 38.730337999999996],
     [-76.34799799999999, 38.686234],
     [-76.322418, 38.679303999999995],
     [-76.275015, 38.712714],
     [-76.238725, 38.712845],
     [-76.200334, 38.670774],
     [-76.175159, 38.673235999999996],
     [-76.1701618745873, 38.6408420471501],
     [-76.165435, 38.6102],
     [-76.203065, 38.610741],
     [-76.23118699999999, 38.61401],
     [-76.279589, 38.609519999999996],
     [-76.290043, 38.569158],
     [-76.277461, 38.541851],
     [-76.33636, 38.492235],
     [-76.280551, 38.403143],
     [-76.25, 38.362304],
     [-76.257667, 38.324855],
     [-76.217613, 38.305682999999995],
     [-76.135513, 38.232185],
     [-76.088639, 38.192648999999996],
     [-76.095548, 38.125122999999995],
     [-76.048692, 38.086728],
     [-76.005904, 38.077169999999995],
     [-76.011916, 38.122214],
     [-76.031988, 38.187419999999996],
     [-76.038935, 38.254932],
     [-75.9445, 38.249145],
     [-75.9237660824283, 38.246285277002],
     [-75.888513, 38.241423],
     [-75.8754473114647, 38.219709301961004],
     [-75.864104, 38.200858],
     [-75.942375, 38.187066],
     [-75.937089, 38.124209],
     [-75.86381, 38.100968],
     [-75.858881, 38.060134999999995],
     [-75.857507, 38.038778],
     [-75.898956, 37.974514],
     [-75.892686, 37.916848],
     [-75.860727, 37.91831],
     [-75.78381499999999, 37.972594],
     [-75.722662, 37.971309999999995],
     [-75.66971099999999, 37.950796],
     [-75.624341, 37.994211],
     [-75.242266, 38.027209],
     [-75.19379599999999, 38.096013],
     [-75.17739399999999, 38.130013999999996],
     [-75.14322899999999, 38.220475],
     [-75.102947, 38.311524999999996],
     [-75.085518, 38.32427],
     [-75.04893899999999, 38.451263],
     [-75.18545499999999, 38.451012],
     [-75.3412873203482, 38.4524365259555],
     [-75.479283, 38.453697999999996],
     [-75.693721, 38.460128],
     [-75.70038199999999, 38.542743],
     [-75.701777515245, 38.5607669290786],
     [-75.707551, 38.635335],
     [-75.707555026429, 38.6353853550599],
     [-75.72310269333269, 38.8298265565277],
     [-75.7481548142541, 39.143131730959695],
     [-75.7564352155685, 39.246687537125304],
     [-75.7604414164505, 39.296789621100096],
     [-75.76689499999999, 39.377499],
     [-75.76690460670919, 39.3776515935512],
     [-75.788596, 39.722198999999996],
     [-76.13569742699019, 39.7217675506067],
     [-76.23327934711659, 39.7216462556279],
     [-76.233485, 39.721646],
     [-76.2396837411146, 39.7216419899246],
     [-76.41897999999999, 39.721526],
     [-76.5694491257313, 39.721458570752695],
     [-76.71577099999999, 39.721393],
     [-76.7870971997576, 39.72104814611129],
     [-76.991062, 39.720062],
     [-76.9993180263332, 39.7200676723526],
     [-77.21702375523739, 39.720217248385396],
     [-77.23995, 39.720233],
     [-77.45943341952389, 39.720229171644995],
     [-77.4691450036804, 39.72022900225],
     [-77.469274, 39.720228999999996],
     [-77.768644, 39.721537999999995],
     [-78.075861, 39.722448],
     [-78.09897069616669, 39.722466194428094],
     [-78.342593, 39.722657999999996],
     [-78.3428335185744, 39.722658292926496],
     [-78.380477064564, 39.72270413884],
     [-78.723578, 39.723122],
     [-78.80829952962159, 39.7230709562769],
     [-78.9284161298889, 39.7229985874409],
     [-79.045576, 39.722927999999996],
     [-79.3924584050224, 39.7214393586401],
     [-79.47666199999999, 39.721078]]]],
  'type': 'MultiPolygon'},
 'properties': {'AFFGEOID': '0400000US24',
  'ALAND': 25151100280,
  'AWATER': 6979966958,
  'GEOID': '24',
  'LSAD': '00',
  'NAME': 'Maryland',
  'STATEFP': '24',
  'STATENS': '01714934',
  'STUSPS': 'MD'},
 'type': 'Feature'}

In [27]:
df['date'] = pd.to_datetime(df['date'])
df.dtypes

date      datetime64[ns]
county            object
state             object
fips             float64
cases              int64
deaths             int64
dtype: object

In [37]:
def covid_stat_on(df,strDate):
  df_temp = df[df['date']==strDate][['fips','state','cases']].copy().dropna().reset_index(drop=True)
  df_temp['fips'] = df_temp['fips'].astype('int').astype('str').apply(lambda x: x.zfill(5))
  return df_temp
covid_stat_on(df,'2020-9-13')

       fips    state  cases
0     01001  Alabama   1576
1     01003  Alabama   4959
2     01005  Alabama    794
3     01007  Alabama    607
4     01009  Alabama   1453
...     ...      ...    ...
3200  56037  Wyoming    318
3201  56039  Wyoming    470
3202  56041  Wyoming    311
3203  56043  Wyoming    110
3204  56045  Wyoming     23

[3205 rows x 3 columns]

In [38]:
map_data = "https://raw.githubusercontent.com/KiranJoshi25/DataVizFall2020_Colab-/master/cb_2018_us_state_20m.json"
m = folium.Map(
            location=[48,-102],
            zoom_start=4)

folium.Choropleth(
    geo_data = map_data,
    name = "covid-19 cases by state",
    legend_name = "actual covid cases",
    data = covid_stat_on(df,'2020-9-13'),
    coloums = ['fips','cases'],
    key_on='feature.properties.GEOID',
    fill_color='RdPu',

    bins=4,
    fill_opacity=0.7,
    line_opacity=0.2,
    nan_fill_color='blue',
    highlight =True,
).add_to(m)
m

TypeError: ignored